baseURL = "https://chevindu.netlify.com/"
title = "Dark Chalk"
theme = "novela"

DefaultContentLanguage = "en"
copyright = "Ideas are bulletproof"

[languages]
  [languages.en]
    title = "Dark Chalk"
    weight = 1
    languageName = "ðŸ‡ºðŸ‡¸"
    contentDir = "content/post/english"
  [languages.si]
    title = "à¶šà·…à·” à·„à·”à¶«à·”"
    weight = 2
    languageName = "ðŸ‡±ðŸ‡°"
    contentDir = "content/post/sinhala"
